### ISSUE TITLE
Error on pt_BR.json

### ISSUE THREAD

**Issue by YskarZwei** [Laerinok/VS_ModsUpdater#14]
There's was an typo and i felt the wording don't hitting quite well so i fixed two entries.
[pt_BR.json.zip](https://github.com/Laerinok/VS_ModsUpdater/files/12697328/pt_BR.json.zip)

**Comment by Laerinok** [comment]
Thanks for the file.
I didn't have as many many time I'd wanted to work on it this week. And I met some issues I yet don't how to deal with.

**Comment by YskarZwei** [comment]
I understand, bro, don't worry.
I rly hope everything goes allright and be resolved nicelly, come back when it's right for you to do so. 👍
