### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by Sir-Ryu** [Laerinok/VS_ModsUpdater#16]
Hello, here is the translation into Spanish for you to add.
[es_ES.zip](https://github.com/Laerinok/VS_ModsUpdater/files/12761757/es_ES.zip)

**Comment by Laerinok** [comment]
Hello. Thanks. I'll add it as soon as possible :)

**Comment by Laerinok** [comment]
Hello,
I've added some new strings for a new feature. I used Deepl to translate, but if you want to have a look, I would really appreciate.

Many thanks


These are the new strings:
	"makePDFTitle" : "Creación de un archivo PDF con la lista de mods",
	"makePDF" : "¿Desea crear un archivo pdf con la lista de mods?",
	"addingmodsinprogress" : "Añadiendo mods actuales...",
	"makingpdfended" : "Creación del archivo PDF completada.",
	"pdfTitle" : "Lista de mods instalados"
	
	English :
	"makePDFTitle" : "Creation of a PDF file of the mod list",
	"makePDF" : "Would you like to create a pdf file of the mod list?",
	"addingmodsinprogress" : "Adding mods in progress...",
	"makingpdfended" : "PDF creation completed.",
	"pdfTitle" : "Installed mods"

**Comment by Sir-Ryu** [comment]
Hello,

Thank you for sharing. I have already reviewed the new strings and the translation is very good. Well done. If you need help with anything else, let me know.

Regards.
