### ISSUE TITLE
Blacklist the .idea folder

### ISSUE THREAD

**Issue by Vlammar** [Laerinok/VS_ModsUpdater#20]
You should blacklist the .idea folder in the git ignore.
Then you need to do: `git checkout master -- .gitignore`
And lastly remove the .idea folder from the git tree

`git rm --cached -r .idea`

**Comment by Laerinok** [comment]
Je verrai ça. Je me souviens m'être posé la question en effet. J'ai encore beaucoup de mal avec Git. Je découvre peu à peu et je galère encore 1 fois sur 2 pour envoyer mes commits ou synchroniser avec ma VM linux...
Je débute Python depuis quelques mois seulement, et j'ai découvert Git cet été histoire de pouvoir partager les sources. Mais j'utilise pas beaucoup et du coup ça rentre très doucement.
Du coup je prends mon temps ;)

Merci pour les infos.

PS : Ce n'est pas suffisant si je rajoute manuellement le dossier .idea au gitignore ? Je n'utilise pas git directement en console, juste son intégration via pycharm.

**Comment by Laerinok** [comment]
Ah, voila j'ai retrouvé pourquoi j'avais gardé le .idea. Enfin j'imagine que c'est pour ça. C'était un commentaire de Pycharm à la fin du .gitignore :

```
# PyCharm
#  JetBrains specific template is maintainted in a separate JetBrains.gitignore that can
#  be found at https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
#  and can be added to the global gitignore or merged into this file.  For a more nuclear
#  option (not recommended) you can uncomment the following to ignore the entire idea folder.
#.idea/
```

**Comment by Vlammar** [comment]
Sur d'autres projets que j'ai ça ne m'a jamais posé de problèmes Je crois que c'est si tu utilises le gitignore qui est dans le .idea que ça pose probleme.
