### ISSUE TITLE
requirements.txt missing, had trouble getting dependencies satisfied.

### ISSUE THREAD

**Issue by Zachs-Kappler** [Laerinok/VS_ModsUpdater#28]
When running either the shell script or python script with Fedora Linux 39, I get the following:
```
Traceback (most recent call last):
  File "/VS_ModsUpdater/VS_ModsUpdater.py", line 43, in <module>
    from fpdf import FPDF, YPos, XPos
ImportError: cannot import name 'YPos' from 'fpdf' (/usr/local/lib/python3.12/site-packages/fpdf/__init__.py)
```
I figured it was a missing dependency, most likely fpdf, so I used pip to install it. Doing so gave me the same error.

The fix was to specifically install the fpdf2 package through pip, which I had to search online through PyPI to find out there was more than one version of FPDF with a different name.

It would also be a good idea to create a requirements.txt with all the libraries that need to be installed from pip to prevent missing dependency headaches like this.

**Comment by Laerinok** [comment]
Hello,
Thanks for your feedback. I've added the requirements.txt.
I am learning Python and this is my first script. So there are many things I don't know. This script was made by adding some new features and knowledges over the time. I am affraid that at the end it will become a mess...

Moreover, I am not a regular Linux user. I have not yet test the v1.3.0 on my VM and I won't have many times these next days to test it. But I will do it as soon as posisble.
