### ISSUE TITLE
fix: pdf generation fails when expected font is not installed

### ISSUE THREAD

**Issue by ApacheTech** [Laerinok/VS_ModsUpdater#33]
### Library Name and version
 * VS_ModsUpdater 1.3.5

### Describe the bug
PDF file generation fails when the DejaVuSerif font is not installed on the host system.

### Expected behaviour
PDF file generation should continue with a fallback font, or embed the fonts it expects to use within the generator.

### Actual behaviour
PDF file is not created, and a log file is created.

```
2024-03-22 02:02:05 : Traceback (most recent call last):
  File "VS_ModsUpdater.py", line 807, in makepdf
  File "fpdf\fpdf.py", line 1840, in add_font
FileNotFoundError: TTF Font file not found: C:\Windows\Fonts\DejaVuSerif.ttf
```

### Reproduction Steps
1. Ensure DejaVuSerif is not installed on host machine.
2. Run the VS_ModsUpdater application.
3. Choose the option to create a PDF file.

### Environment
OS: Windows 10
Game Version: 1.19.4
Config:
```
[ModsUpdater]
# info about the creation of the config.ini file
ver = 1.3.5
system = Windows
# enable or disable force_update for every mods. if enabled, it will download the last version for all mods, even if the version is already the latest. (true/false default=false)
force_update = false

[ModPath]
path = C:\Games\Vintage Story\data\Mods

[Language]
# to change the default language, uncomment the line below and set the desired language ('lang' folder)
language = en_US

[Game_Version_max]
# select the maximum game version for which mods can update themselves (ex: 100.0.0, 1.18, 1.18.1). default: 100.0.0 (to have all versions)
version = 100.0.0

[Mod_Exclusion]
# to exclude a mod from the update, add the name (with extension) of the mod's zip file after = (one per line)
mod1 = 
mod2 = 
mod3 = 
mod4 = 
mod5 = 
mod6 = 
mod7 = 
mod8 = 
mod9 = 
mod10 = 
```

**Comment by Laerinok** [comment]
Thanks for report.
First I used an embeded font, but there was an issue with cyrillic language which was not recognized.
I thought DejaVuSerif.ttf was a default font on System as I have natively on my Windows/linux VM. But maybe it is only on french system.

I will look for this.

**Comment by Laerinok** [comment]
Should be fixed. I added font in a folder. I think I will see later if I can embed them in the exe file.
