### ISSUE TITLE
Error updating certain mods, related to the modinfo.json

### ISSUE THREAD

**Issue by Sir-Ryu** [Laerinok/VS_ModsUpdater#36]
Hello, how are you Laerinok? I've been testing the new version v1.3.6 and it turned out very well, but it seems there's a bug with the modinfo.json identifier. With some mods, it throws an error, but something curious is that it downloads and replaces the mod files. However, in the console, it only throws an error message and doesn't identify that it has been updated. Here are the .logs for you.
By the way, for some reasons, I switched from Windows 11 to Windows 10, and the v1.3.4 that worked fine on Windows 11 gave me errors with all the mods just as it started up, but it got fixed with v1.3.5, so it's quite possible that this error is an incompatibility with Windows 10.
[logs.zip](https://github.com/Laerinok/VS_ModsUpdater/files/14810492/logs.zip)

**Comment by Laerinok** [comment]
Hello,
I'm fine thanks. And you?
I quickly had a look to the logs files. It seems the pb is about connection to the moddb (TimeoutError: [WinError 10060])
It can occur if the connection is lost or if you are blocked by the site. 
I remember you have a lot of mods. Probably the site has anti-scraping code and your manys connections to mods warm it and blocks.
It's just an idea...

I will investigate, but probably not this week-end.

For the other "issue", I am on Windows 10. So I can't test. But indeed it's a strange behavior. If you get more details, I'm curious to know.

**Comment by Sir-Ryu** [comment]
I'm doing well, I'm working on translating a couple of mods.

Ummm, the error (TimeoutError: [WinError 10060]) I can't think of what could be causing it. I have 50mb fiber optic internet, and it's very stable, and this is the first time I've encountered this error until now that I switched to Windows 10. Although it's possible that they have implemented anti-scraping code in the last month, I don't rule it out, but the curious thing is that the download reaches 100/100 and right there it gets stuck for a moment and throws the error.

Regarding the other "problem," I'm on Windows 10 and couldn't replicate the error. I think I fixed it because just today I started updating PowerShell, CMD, uninstalling drivers and reinstalling them, etc., so that "bug" is already ruled out.

**Comment by Laerinok** [comment]
> I have 50mb fiber optic internet,
Well it may sound logic. Your connection is very fast. So the script connects the database very quickly. More than a human would do. So you the request is blocked. I don't know if it's the problem, that's just an hypothesis.
It seems that only the request to test if the link exist makes the issue. The download works. That's why you have the error message but the file is downloaded. So maybe I could delete the test. I don't really know if it is really necessary.
That's the "problem" with learning people. We do things but they are not always good/useful ^^.
I must say that, when I started the script, I never thought I would make such a script neither it would be downloaded so much times.

OK. Glad to know the other problem is fixed :)

**Comment by Sir-Ryu** [comment]
Yes, I understand. I came up with a couple of ideas that could fix it:

The first one would be to make the test able to loop in case of an error, and be able to retry validating the link, say, about 2 times, for example.

The other idea is to add a test that detects and validates the start and completion of the download, returning a Boolean value, TRUE if it downloaded correctly, connecting it to the link test, and changing the Boolean value in case the link test encountered an error, also to TRUE.

> That's the "problem" with learning people. We do things but they are not always good/useful ^^.
If I understand you completely, I'm also a student, but in web programming. However, I don't entirely agree with you. Sometimes we create things that may seem useless, but it could be that we aren't using them correctly, or they might be very useful in a future project. So rather than a "problem," it's better to see it as a skill that can be refined and improved with experience, through trial and error.

> I must say that, when I started the script, I never thought I would make such a script neither it would be downloaded so much times. But I've learnt so many things since I started :)
It's true, sometimes we underestimate the potential of our creations. But every challenge teaches us something new.
