### ISSUE TITLE
No mods in mods folder when there are mods

### ISSUE THREAD

**Issue by auyylaso** [Laerinok/VS_ModsUpdater#42]
![image](https://github.com/Laerinok/VS_ModsUpdater/assets/70453553/2ef90af4-8051-4972-b5de-9335260b3b36)
Attached is a photo of Mods in the DIR but it says there are no mods. Yes the DIR is correctly set to the right path in the config file

[ModsUpdater]
# info about the creation of the config.ini file
ver = 1.4.0
system = Windows
# enable or disable force_update for every mods. if enabled, it will download the last version for all mods, even if the version is already the latest. (true/false default=false)
force_update = false
# allow to disable or enable update of mod in dev or prerelease (true/false default=false).
disable_mod_dev = false

[ModPath]
path = C:\Users\REDACTED\AppData\Roaming\VintagestoryData\Mods

[Language]
# to change the default language, uncomment the line below and set the desired language ('lang' folder)
language = en_US

[Game_Version_max]
# select the maximum game version for which mods can update themselves (ex: 100.0.0, 1.18, 1.18.1). default: 100.0.0 (to have all versions)
version = 100.0.0

[Mod_Exclusion]
# to exclude a mod from the update, add the name (with extension) of the mod's zip file after = (one per line)
mod1 = 
mod2 = 
mod3 = 
mod4 = 
mod5 = 
mod6 = 
mod7 = 
mod8 = 
mod9 = 
mod10 =

**Comment by Laerinok** [comment]
Hello,
This is because you unziped files in the mods directory. You don't have to do. Let the .zip file instead the folder.
